### ISSUE TITLE
Adding game rule to config file

### ISSUE THREAD

**Issue by HessyD** [Estecka/mc-Preferred-Gamerules#2]
Added game rule with gamerule.* . Start server and it will not start due to missing command. Is there a command need before? Can you give example how it should look in config file?

**Comment by Estecka** [comment]
There shouldn't be any other step to this, the mod doesn't include any command. Can I see the full log ?

**Comment by Estecka** [comment]
In most cases, a malformatted config file shouldn't even lead to a crash, so I suspect there's another mod at play here.

**Comment by Estecka** [comment]
And to answer your other question, each line would look something like this: 
```properties
gamerule.keepInventory=true
```
